Frontend:
  impl: LoadStoreTrace
  clock_ratio: 64
  num_expected_insts: 1000
  path: ./HBM_test/trace/stream_LS_1000_1ch.trace

  Translation:
    impl: NoTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 1

  DRAM:
    impl: HBM2
    org:
      preset: HBM2_8Gb_40Ch_2pch
    timing:
      preset: HBM2_2.4Gbps

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 4
    plugins:

  AddrMapper:
    impl: RoCo2BaCo1RaCh
    # impl: RoBaRaCoCh
