Frontend:
  impl: LoadStoreTrace
  clock_ratio: 1
  num_expected_insts: 1000
  path: ./HBM_test/trace/stream_LS_1000_1ch.trace

  Translation:
    impl: NoTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 1

  DRAM:
    impl: HBM3
    org:
      preset: HBM3_8Gb
    timing:
      preset: HBM3_2Gbps 

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 4
    plugins:

  AddrMapper:
    # impl: RoCo2BaCo1RaCh
    impl: RoBaRaCoCh
