Frontend:
  impl: LoadStoreTrace
  clock_ratio: 8
  num_expected_insts: 1000
  path: stream_LS_1000.trace

  Translation:
    impl: NoTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: HBM3
    org:
      preset: HBM3_8Gb
      channel: 1
    timing:
      preset: HBM3_2Gbps 

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 4
    plugins:

  AddrMapper:
    impl: RoBaRaCoCh
